### ISSUE TITLE
AFC support

### ISSUE THREAD

**Issue by TomasHubelbauer** [norman784/libimobiledevice-node#10]
Hi, I am just beginning to learn about USBMUX and all the stuff surrounding iPhone to Mac/PC communication, so some associations might be escaping me right now. With that said, I wonder if this library can be used to communicate with the AFC file system service?

I am interested in syncing photos and videos back and forth between a USB connected iPhone and a Mac or a PC programmatically. My understanding is that libmobiledevice would be the right tool to do jus that as it wraps usbmux and then provides APIs for various services like AFC.

I have checked the TODO section in the README but it makes no mention of AFC. Is that just because it is not on the roadmap or is there another approach that would be needed for it?

Also, can the implemented idevicebackup2 lib be used to sync photos and videos selectively? I don't think so based on inspecting its API but asking just in case.

**Comment by TomasHubelbauer** [comment]
Update: I have found https://github.com/mceSystems/libijs which has AFC support so I decided to use that. I'm still interested to see if you plan on supporting it, but since I have a solution now I am going to close the issue.

**Comment by norman784** [comment]
This library is an incomplete binding of the [libimobiledevice](https://www.libimobiledevice.org/). I'm not using this library anymore so I'm not sure if the original library supports it.
