### ISSUE TITLE
Unable to turn off encryption

### ISSUE THREAD

**Issue by bhupendra-mp** [norman784/libimobiledevice-node#12]
I am using the backup2 with following options but it is giving me error:

```
Can't get password input in non-interactive mode. Either pass password(s) on the command line, or enable interactive mode with -i or --interactive.
```

```
const libBackupOptions = {
      encryption: {
        status: 'off',
        password: '000000'
      }
    };
```

If I pass interactive: true, which I should not. Then I just get following in on('data') event and nothing else.
```
Started "com.apple.mobilebackup2" service on port 49295.
Negotiated Protocol Version 2.1
```
I am using macOS Catalina. I installed latest version of libimobiledevice on my Mac mini using brew and following command works fine.
```
idevicebackup2 encryption off 000000
```

Is it the limitation of this library?

**Comment by didix21** [comment]
Sorry for answering late, but probably the problem is native libimobiledevice is outdated.

**Comment by didix21** [comment]
After updating libimobiledevice, I can see the problem persist. The following error is shown:

```bash
error:  ERROR: Can't get password input in non-interactive mode. Either pass password(s) on the command line, or enable interactive mode with -i or --interactive.
```

Moreover, I've been able to find the problem and it's a problem in the native part implemented in libimobiledevice-node.
