### ISSUE TITLE
New Release candidate 0.2.7

### ISSUE THREAD

**Issue by didix21** [norman784/libimobiledevice-node#7]
I think we can create a new release candidate and update the npm release @norman784  
New features:
    - The package can be used on windows.
    - Added binaries idevicepair.
    - Bug #4 fixed.

**Comment by norman784** [comment]
I really think that too, I finished to setup a team in npm so if you like I can add you as a developer there and you will be able to publish new releases, the only thing I need if your npm username, let me know if that works for you.

**Comment by didix21** [comment]
It will be a pleasure. My username is **didix21**
