### ISSUE TITLE
error LNK2001: unresolved external symbol

### ISSUE THREAD

**Issue by iap2** [norman784/libimobiledevice-node#8]
Hi. I'm getting a bunch of these errors when building on windows during the node-gyp rebuild step. Have not made any changes to project. Build for osx went through without any problems. Any help would be greatly appreciated. 

example errors:
id.obj : error LNK2001: unresolved external symbol idevice_device_list_free
info.obj : error LNK2001: unresolved external symbol idevice_new
backup2.obj : error LNK2001: unresolved external symbol plist_array_get_item

**Comment by didix21** [comment]
If you have closed this issue I suppose your problem has been solved. Anyways, be sure that you fulfill all the requeriments described on the **README**
